import streamlit as st
#import database as db
import random
import time
from PIL import Image


loader_html="""
        <div class="loadingio-spinner-spinner-5kfh33l3w67"><div class="ldio-kv3v74jczi">
        <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
        </div></div>
        <style type="text/css">
        @keyframes ldio-kv3v74jczi {
        0% { opacity: 1 }
        100% { opacity: 0 }
        }
        .ldio-kv3v74jczi div {
        left: 94px;
        top: 48px;
        position: absolute;
        animation: ldio-kv3v74jczi linear 1s infinite;
        background: #1d3f72;
        width: 12px;
        height: 24px;
        border-radius: 6px / 12px;
        transform-origin: 6px 52px;
        }.ldio-kv3v74jczi div:nth-child(1) {
        transform: rotate(0deg);
        animation-delay: -0.9166666666666666s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(2) {
        transform: rotate(30deg);
        animation-delay: -0.8333333333333334s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(3) {
        transform: rotate(60deg);
        animation-delay: -0.75s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(4) {
        transform: rotate(90deg);
        animation-delay: -0.6666666666666666s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(5) {
        transform: rotate(120deg);
        animation-delay: -0.5833333333333334s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(6) {
        transform: rotate(150deg);
        animation-delay: -0.5s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(7) {
        transform: rotate(180deg);
        animation-delay: -0.4166666666666667s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(8) {
        transform: rotate(210deg);
        animation-delay: -0.3333333333333333s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(9) {
        transform: rotate(240deg);
        animation-delay: -0.25s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(10) {
        transform: rotate(270deg);
        animation-delay: -0.16666666666666666s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(11) {
        transform: rotate(300deg);
        animation-delay: -0.08333333333333333s;
        background: #1d3f72;
        }.ldio-kv3v74jczi div:nth-child(12) {
        transform: rotate(330deg);
        animation-delay: 0s;
        background: #1d3f72;
        }
        .loadingio-spinner-spinner-5kfh33l3w67 {
        width: 200px;
        height: 200px;
        display: inline-block;
        overflow: hidden;
        background: #ffffff;
        }
        .ldio-kv3v74jczi {
        width: 100%;
        height: 100%;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0; /* see note above */
        }
        .ldio-kv3v74jczi div { box-sizing: content-box; }
        /* generated by https://loading.io/ */
        </style>
        """

def get_bf():
    lst=["Idli", "Dosa", "Vada Sambar", "Chitranna", "Upma", "Poori", "Pongal"," Bisi Bele Bath", "Set Dosa","Rava Idli"]
    item=random.choice(lst)
    placeholder = st.empty()
    placeholder=st.markdown(loader_html,unsafe_allow_html=True)
    time.sleep(5)
    placeholder.empty()
    return item

def get_l():
    lst2=["Roti Paneer","Egg rice","Curd Rice","Anna Sambar","Chapati","Tomoto Rice","Ragi Mudde","Veg Biryani","pulao","Fried Rice"]
    item=random.choice(lst2)
    placeholder = st.empty()
    placeholder=st.markdown(loader_html,unsafe_allow_html=True)
    time.sleep(5)
    placeholder.empty()
    return item

def get_d():
    lst3=["Anna Sambar","chapati with curd","Roti Paneer","Tomoto Rice","Onion Dosa","Paneer Fried Rice"]
    item=random.choice(lst3)
    placeholder = st.empty()
    placeholder=st.markdown(loader_html,unsafe_allow_html=True)
    time.sleep(5)
    placeholder.empty()
    return item

def main():
    st.set_page_config(page_title="Food Recommendation",page_icon=":shallow_pan_of_food:",layout="wide")
    st.title("Wellcome There Your confused ")
    st.subheader("What to eat 	:joy:")
    option = st.selectbox(
    'What **:green[TIME]** is this :hourglass_flowing_sand:?',
    ('Select','Breakfast 🍞🍳', 'Lunch 🍜🍝', 'Dinner 🍱🍲'))
    if option == 'Breakfast 🍞🍳':
        st.subheader('Hey There Good Morning! 🌅 ')
        submit_bf=st.button("Get My BreakFast")
        if submit_bf:
            r=get_bf()
            if r:
                cmp="Hey we have suggestion for you ***:orange["+r+"]***:smile:"
                st.write(cmp,unsafe_allow_html=True)
                st.snow()

    if option == 'Lunch 🍜🍝':
        st.subheader('Hey There Good Afternoon! 🌤️ \n :blue[Click on Here]')
        submit_bf=st.button("Get My Lunch")
        if submit_bf:
            r=get_l()
            if r:
                cmp="Hey we have suggestion for you ***:orange["+r+"]***:smile:"
                st.write(cmp,unsafe_allow_html=True)
                st.snow()

    if option == 'Dinner 🍱🍲':
        st.subheader('Hey There Good Evening! 🌆 \n :blue[Click on Here]')
        submit_bf=st.button("Get My Dinner")
        if submit_bf:
            r=get_d()
            if r:
                cmp="Hey we have suggestion for you ***:orange["+r+"]***:smile:"
                st.write(cmp,unsafe_allow_html=True)
                st.snow()

    if option == "Select":
        image = Image.open('images/cooking.jpg')
        st.image(image, caption='Restaurants Kitchen 🍴')



if __name__ == '__main__':
    main()